export declare const audioContext: any;
export declare const gainNode: any;
export declare const activeInstance: any;
export declare const init: () => void;
export declare const audioBuffer: any;
export declare const isPlaying: any;
export declare const sourceNode: any;
export declare const pauseTime: any;
export declare const startTime: any;
export declare const load: (item?: string) => Promise<boolean | undefined>;
export declare function play(): true | undefined;
export declare const pause: () => boolean;
export declare const stop: () => void;
export declare function setVolume(level: any): void;
export declare const seek: (time: any) => boolean;
export declare const _progressCallback: any;
export declare const _animationFrameId: any;
export declare function _trackProgress(): void;
export declare function onProgress(callback: any): void;
export declare function destroy(): void;
